### ISSUE TITLE
Empty values interrupt injection (PropertyAnnotationProcessor)

### ISSUE THREAD

**Issue by pblanche** [benas/easy-properties#3]
It is not unusal to have empty values in a property file. Unfortunately an empty value leads to an exception and further properties are not injected. Is this a bug or should this be the normal behaviour?
MY.KEY_1=value1
MY.KEY_2=value2
MY.KEY_3=                           <<<<<<<<<<<<<< throws exception and interrupts injection
MY.KEY_4=value4

**Comment by benas** [comment]
Sorry for the late reply.

It seems like this how It was implemented. This is a design issue. Projector should silently ignore empty values and warn about missing keys.

I just fixed that in version 1.1.1-SNAPSHOT (deployed to maven central).

**Comment by pblanche** [comment]
Thank you very much!
Am 08.08.2015 um 00:26 schrieb Mahmoud Ben Hassine:
